#+title: paw org protocol
paw org protocol is an Emacs org protocol companion tool with configurable protocol(s).

The selected information and the context are sent to Emacs via org-protocol.

* Download
1. Firefox & Firefox Android https://addons.mozilla.org/en-US/firefox/addon/emacs-paw
2. Chrome: https://chromewebstore.google.com/detail/paw/ofhodjclfalelhgjbfmdddekoghamlge
3. Brave: Same as Chrome, but need to add ~@@||localhost^~ into ~Create custom filters section~ of ~brave://settings/shields/filters~ if you need paw-server features.

* Configuration

*** Parameters
- ~Template~: the template we used for org-capture
- ~url~: The current page's url
- ~title~: The current page's title
- ~note~: The parent sentence of the selected word/area
- ~body~: The selected word/area
- ~Server~: The paw-server address
- ~Protocol(s)~: Please check below section

*** Protocols
**** Example: Register an org-protocol of opening the current page's url of chrome in eaf
#+begin_src emacs-lisp

(add-to-list 'org-protocol-protocol-alist 
             '("Eaf Browser"
               :protocol "eaf-browser"
               :function org-protocol-eaf-browse
               :kill-client t))

(defun org-protocol-eaf-browse (arg)
  (let ((url (plist-get arg :url))) ;; we also have title, note, and body, here we only use url as example
    (eaf-browse url))
  nil)
#+end_src

Setup the Protocol(s) in chrome extension, we support two types format of Protocol(s):
***** Json Array (New, supported from paw extension 1.0.18)
#+begin_src js
[
  { "protocol": "paw", "format": "text" },
  { "protocol": "eaf-browser", "format": "text" },
  { "protocol": "capture-html", "format": "html" },
  { "protocol": "wallabag", "format": "text", "download": true }
]
#+end_src
You can choose ~text~ or ~html~ ~format~. It will pass the selected area as ~body~ in org-protocol link to Emacs.

If you install python command line tool [[https://pypi.org/project/emacs-paw/][emacs-paw]], and if ~download~ is true, the current page's html will send to paw-server, saved into ~save-dir~, trigger org-protocol link, finally you can handle the html file in Emacs.

***** Or comma-sperated text (Old format)
#+begin_src text
paw,eaf-browser
#+end_src

The body will be ~text~ by default.

*** paw-server
1. Install python command line tool [[https://pypi.org/project/emacs-paw/][emacs-paw]]
2. Run paw-server by
        #+begin_src sh
        paw run_server --database /home/damonchan/org/paw.sqlite --save-dir /tmp/source.html --port 5001 --wallabag-host https://example.com --wallabag-username username --wallabag-password password --wallabag-clientid clientid --wallabag-secret secret
        #+end_src
If you installed [[https://github.com/chenyanming/paw][paw.el]], you can also use M-x ~paw-server~

*** Supported Emacs Packages
- https://github.com/chenyanming/paw: Send word to Emacs and show on paw-view-note
- https://github.com/chenyanming/wallabag.el: Open the wallabag article or save the page to wallabag
- https://github.com/chenyanming/calibredb.el: Open ebook directly in browser

** Similar Projects
- https://github.com/alphapapa/org-protocol-capture-html
